### ISSUE TITLE
FPGemminiRocketConfig compilation error

### ISSUE THREAD

**Issue by ssorbetto** [ucb-bar/gemmini#353]
Chipyard tag: v1.11.0
Gemmini commit: 8c8b38b

Error Message:
```
mkdir -p /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig
cp -f /scratch/lucy/chipyard-g/generators/testchipip/src/main/resources/testchipip/bootrom/bootrom.rv64.img /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig/bootrom.rv64.img
cp -f /scratch/lucy/chipyard-g/generators/testchipip/src/main/resources/testchipip/bootrom/bootrom.rv32.img /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig/bootrom.rv32.img
mkdir -p /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig
(set -o pipefail && 	cd /scratch/lucy/chipyard-g && java -cp /scratch/lucy/chipyard-g/.classpath_cache/chipyard.jar chipyard.Generator  --target-dir /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig --name chipyard.harness.TestHarness.FPGemminiRocketConfig --top-module chipyard.harness.TestHarness --legacy-configs chipyard:FPGemminiRocketConfig   | tee /scratch/lucy/chipyard-g/sims/vcs/generated-src/chipyard.harness.TestHarness.FPGemminiRocketConfig/chipyard.harness.TestHarness.FPGemminiRocketConfig.chisel.log)
Picked up JAVA_TOOL_OPTIONS: -Xmx8G -Xss8M -Djava.io.tmpdir=/scratch/lucy/chipyard-g/.java_tmp
(3,List(UInt<7>(123)))
L2 InclusiveCache Client Map:
	0 <= serial_tl_0
	1 <= Core 0 DCache
	2 <= stream-reader
	3 <= stream-writer
	4 <= Core 0 ICache

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at ... ()
	at chipyard.stage.phases.PreElaboration.$anonfun$transform$1(PreElaboration.scala:35)
	at ... ()
	at ... (Stack trace trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace)
Caused by: java.lang.AssertionError: can't create Mux with heterogeneous types class chisel3.SInt and class gemmini.Float
	at chisel3.cloneSupertype$.$anonfun$apply$4(Data.scala:197)
	at scala.collection.IterableOnceOps.reduceLeft(IterableOnce.scala:769)
```

Issue: `AccumulatorScale.scala` with the `iexp` activation function and floating point

Replacing `iexp` with `igelu` logic allows FPGemminiRocketConfig to build

**Comment by hansa31** [comment]
Replace, 
z_iexp_saturated := Mux((5 until 16).map(z_iexp.asUInt(_)).reduce(_ | _), 32.S, z_iexp) 
with 
z_iexp_saturated := Mux((5 until 16).map(z_iexp.asUInt(_)).reduce(_ | _), 32.S.asTypeOf(z_iexp), z_iexp)
